name: ğŸš€ Deploy aliyun on push
on:
  push:
    branches:
      # masteråˆ†æ”¯ï¼Œä½ ä¹Ÿå¯ä»¥æ”¹æˆå…¶ä»–åˆ†æ”¯
      - master
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§
        run:
            npm install && npm run docs:build
        env:
            NODE_OPTIONS: '--max_old_space_size=4096'
      - name: ğŸ“‚ Sync files
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # ç§é’¥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scpå‚æ•°
          ARGS: "-avzr --delete"
          # æºç›®å½•ï¼Œç¼–è¯‘åç”Ÿæˆçš„æ–‡ä»¶ç›®å½•
          SOURCE: "./public/"
          # æœåŠ¡å™¨ipï¼šæ¢æˆä½ çš„æœåŠ¡å™¨IP
          REMOTE_HOST: "47.94.99.238"
          # ç”¨æˆ·
          REMOTE_USER: "root"
          # ç›®æ ‡åœ°å€ ä½ åœ¨æœåŠ¡å™¨ä¸Šéƒ¨ç½²ä»£ç çš„åœ°æ–¹
          TARGET: "/var/www/hks-function"
